[package]
name = "utilities"
version = "0.1.0"
authors = ["Roman Podoliaka <roman.podoliaka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "1.0"
statrs = "0.12.0"
