name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

defaults:
  run:
    shell: bash

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  cargo-test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust-version:
          - stable

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-version }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: test

  cargo-rustdoc:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1

       - uses: actions-rs/toolchain@v1
         with:
           toolchain: stable
           profile: minimal
           override: true

       - uses: actions-rs/cargo@v1
         with:
           command: rustdoc
           args: -- -D intra-doc-link-resolution-failure
